### ISSUE TITLE
Search not working for certain commands

### ISSUE THREAD

**Issue by kanna6501** [excalith/Interactive-Git-Cheatsheet#2]
I was trying to lookup git "branch" but I noticed that the search ranks "clone", "status" and "commit" before actually giving the result. Then I tried testing other stuff and they weren't working either. 
Examples:
commit - ranks "add" first then commit
tag - ranks "add", "commit", "rm" before showing the actual "tag" command.

## Expected Behaviour
Display the correct search result.
## Actual Behaviour
Displays other results before the searched one.
## Steps To Reproduce
- Search up a command (like branch, tag, or commit)
- The results are not what was searched.

**Comment by excalith** [comment]
Hey there, this was actually designed this way intentionally. For instance, whenever you type 'branch' it shows every section contains string as 'branch' to help finding related information since each command has variety of options which may contain command options that effect branches. I agree about it doesn't make sense at the beginning. I will fix it to search only for keywords, and hopefully update them within json data to show more related results.

**Comment by excalith** [comment]
Hopefully this does the trick :) I have commented old regex, maybe in the future we can add a settings button where you can switch back to intensive search mode
